In [1]:
import os
import django
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'rest.settings')
os.environ["DJANGO_ALLOW_ASYNC_UNSAFE"] = "true"
django.setup()

In [2]:
import numpy as np
import pandas as pd
import pandas_ta as ta
from ta import add_all_ta_features
from ta.utils import dropna
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
from bourse_refs_api.models import StockHistory

In [4]:
df = pd.DataFrame(StockHistory.objects.all().values())
df = df.sort_values('date').reset_index(drop=True)
df = dropna(df)

In [5]:
df

,id,stock_id,date,max_price,min_price,last_price,last_deal_price,first_price,yesterday_price,value,volume,count
0,199299,60350996279289096,2018-07-01,3025.0,2875.0,2878,2875,3025.0,3026,43856886482,15240753,623
1,199444,66599109405217136,2018-07-01,11309.0,10512.0,10634,10512,10655.0,10800,58424918,5494,18
2,199443,66142616039907392,2018-07-01,10099.0,9570.0,9797,9799,10000.0,9989,1246590524,127241,58
3,199442,65671173927025648,2018-07-01,3560.0,3351.0,3449,3420,3498.0,3417,4847834909,1405640,267
4,199441,65018804181564928,2018-07-01,973.0,909.0,922,914,950.0,956,982481651,1065051,211
...,...,...,...,...,...,...,...,...,...,...,...,...
424152,465128,38713440086361984,2021-08-10,11550.0,11300.0,11532,11550,11550.0,11433,836923048,72576,26
424153,465127,3823243780502959,2021-08-10,11950.0,11410.0,11730,11760,11800.0,11610,15594905390,1329577,407
424154,465126,38568786927478800,2021-08-10,69100.0,66500.0,68530,69080,66900.0,65810,306157538190,4467581,1083
424155,465137,33420285433308220,2021-08-10,126050.0,120000.0,125700,126050,120000.0,120050,75723841080,602402,416
424156,465044,43062880954780880,2021-08-10,15830.0,15100.0,15770,15830,15300.0,15080,83768162780,5311925,1193

In [6]:
df = df.sort_values(['stock_id', 'date'])

In [7]:
df = df.rename(columns={
    'max_price': 'high',
    'min_price': 'low',
    'last_deal_price': 'close',
    'first_price': 'open'
})

In [23]:
def add_cdl_patterns(group):
    try:
        return pd.concat([group, group.ta.cdl_pattern()], axis=1)
    except:
        return pd.DataFrame()

df.groupby('stock_id').apply(add_cdl_patterns)

                                id      stock_id        date     high  \
stock_id
22129017544200    134055   67778.0  2.212902e+13  2019-07-28    870.0
                  134576   68280.0  2.212902e+13  2019-07-29    764.0
                  135093   68812.0  2.212902e+13  2019-07-30    769.0
                  135626   69324.0  2.212902e+13  2019-07-31    785.0
                  136175   69871.0  2.212902e+13  2019-08-03    827.0
...                            ...           ...         ...      ...
71980027636215728 393345  435103.0  7.198003e+16  2021-05-25  34300.0
                  393990  435716.0  7.198003e+16  2021-05-26  30500.0
                  394566  436312.0  7.198003e+16  2021-05-29  31191.0
                  395182  436939.0  7.198003e+16  2021-05-30  29400.0
                  395818  437548.0  7.198003e+16  2021-05-31  28243.0

                              low  last_price    close     open  \
stock_id
22129017544200    134055    783.0       797.0    783.0    870.0
                  134576    718.0       727.0    722.0    719.0
                  135093    672.0       722.0    743.0    718.0
                  135626    728.0       753.0    770.0    731.0
                  136175    770.0       805.0    808.0    800.0
...                           ...         ...      ...      ...
71980027636215728 393345  31034.0     31254.0  31034.0  34300.0
                  393990  29692.0     29706.0  29692.0  30500.0
                  394566  28221.0     28225.0  28221.0  31191.0
                  395182  26814.0     26899.0  26814.0  29400.0
                  395818  25555.0     25602.0  25555.0  28243.0

                          yesterday_price         value  ...  CDL_SPINNINGTOP  \
stock_id                                                 ...
22129017544200    134055              1.0  7.333301e+09  ...              0.0
                  134576            797.0  4.361260e+10  ...              0.0
                  135093            727.0  3.372879e+10  ...              0.0
                  135626            722.0  3.377075e+10  ...              0.0
                  136175            753.0  3.245728e+10  ...              0.0
...                                   ...           ...  ...              ...
71980027636215728 393345          32667.0  1.161759e+09  ...              0.0
                  393990          31254.0  2.985153e+08  ...              0.0
                  394566          29706.0  1.789772e+10  ...              0.0
                  395182          28225.0  2.020671e+10  ...              0.0
                  395818          26899.0  5.938368e+11  ...              0.0

                          CDL_STALLEDPATTERN  CDL_STICKSANDWICH  CDL_TAKURI  \
stock_id
22129017544200    134055                 0.0                0.0         0.0
                  134576                 0.0                0.0         0.0
                  135093                 0.0                0.0         0.0
                  135626                 0.0                0.0         0.0
                  136175                 0.0                0.0         0.0
...                                      ...                ...         ...
71980027636215728 393345                 0.0                0.0         0.0
                  393990                 0.0                0.0         0.0
                  394566                 0.0                0.0         0.0
                  395182                 0.0                0.0         0.0
                  395818                 0.0                0.0         0.0

                          CDL_TASUKIGAP  CDL_THRUSTING  CDL_TRISTAR  \
stock_id
22129017544200    134055            0.0            0.0          0.0
                  134576            0.0            0.0          0.0
                  135093            0.0            0.0          0.0
                  135626            0.0            0.0          0.0
                  136175            0.0            0.0          0.0
...                                 ...            ...          ...
71980027636215728 393345            0.0            0.0          0.0
                  393990            0.0            0.0          0.0
                  394566            0.0            0.0          0.0
                  395182            0.0            0.0          0.0
                  395818            0.0            0.0          0.0

                          CDL_UNIQUE3RIVER  CDL_UPSIDEGAP2CROWS  \
stock_id
22129017544200    134055               0.0                  0.0
                  134576               0.0                  0.0
                  135093               0.0                  0.0
                  135626               0.0                  0.0
                  136175               0.0                  0.0
...                                    ...                  ...
71980027636215728 393345               0.0                  0.0
                  393990               0.0                  0.0
                  394566               0.0                  0.0
                  395182               0.0                  0.0
                  395818               0.0                  0.0

                          CDL_XSIDEGAP3METHODS
stock_id
22129017544200    134055                   0.0
                  134576                   0.0
                  135093                   0.0
                  135626                   0.0
                  136175                   0.0
...                                        ...
71980027636215728 393345                   0.0
                  393990                   0.0
                  394566                   0.0
                  395182                   0.0
                  395818                   0.0

[423872 rows x 74 columns]